### ISSUE TITLE
[J] and [M] restricted card indicators block smooth deck import from thronesdb

### ISSUE THREAD

**Issue by EvadLhorg** [throneteki/throneteki-client#89]
As the title says, when you import a deck from thronesdb, the new [J] and [M] restricted card indicators after the cards name make the deck import via copy&paste not work as smooth as before. you have to remove the indicators manually before the deck is registered as valid

**Comment by stopfstedt** [comment]
Will keep that in mind in case I change those indicators, to let y'all know.
